/*
 * Api1.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using Api1.PCL;
using Api1.PCL.Utilities; 
using Api1.PCL.Http.Client;
using Api1.PCL.Http.Response;
using Api1.Tests.Helpers;
using NUnit.Framework;
using Api1.PCL;
using Api1.PCL.Controllers;
using Api1.PCL.Exceptions;

namespace Api1.Tests
{
    [TestFixture]
    public class APIControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static APIController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().Client;
        }

        /// <summary>
        /// asdasd 
        /// </summary>
        [Test]
        public async Task TestAsdasd() 
        {
            // Parameters for the API call
            string operation = null;

            // Perform API call

            try
            {
                await controller.GetAddressAsync(operation);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

        }

    }
}